CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "ActivityCoopBossInfoSet" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "ActivityId" integer NOT NULL,
    "LastLevel" integer NOT NULL,
    "LastLevelActivateTime" bigint NOT NULL,
    "RefreshCountToday" integer NOT NULL,
    "LastRefreshTime" bigint NOT NULL,
    "DrewCount" integer NOT NULL,
    "GameEndCountToday" integer NOT NULL,
    "LastRefreshEndCountTime" bigint NOT NULL,
    CONSTRAINT "PK_ActivityCoopBossInfoSet" PRIMARY KEY ("PlayerId", "ShardId", "ActivityId")
);

CREATE TABLE "ActivityEndlessChallenges" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "ActivityId" integer NOT NULL,
    "MaxUnlockDifficulty" integer NOT NULL,
    "TodayGameCount" integer NOT NULL,
    "LastGameTime" bigint NOT NULL,
    CONSTRAINT "PK_ActivityEndlessChallenges" PRIMARY KEY ("PlayerId", "ShardId", "ActivityId")
);

CREATE TABLE "ActivityLuckyStars" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "ActivityId" integer NOT NULL,
    "Sequence" integer NOT NULL,
    "Cycle" integer NOT NULL,
    "Free" boolean NOT NULL,
    CONSTRAINT "PK_ActivityLuckyStars" PRIMARY KEY ("PlayerId", "ShardId")
);

CREATE TABLE "ActivityPiggyBanks" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "ActivityId" integer NOT NULL,
    "Exp" integer NOT NULL,
    "ClaimStatus" bigint[] NOT NULL,
    "PaidLevel" integer NOT NULL,
    CONSTRAINT "PK_ActivityPiggyBanks" PRIMARY KEY ("PlayerId", "ShardId", "ActivityId")
);

CREATE TABLE "ActivityUnrivaledGods" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "ActivityId" integer NOT NULL,
    "KeyCount" integer NOT NULL,
    "GuaranteeProgress" integer NOT NULL,
    "ScorePoint" integer NOT NULL,
    "ExchangeRecord" jsonb NOT NULL DEFAULT ('{}'::jsonb),
    "TaskRecord" jsonb NOT NULL DEFAULT ('{}'::jsonb),
    CONSTRAINT "PK_ActivityUnrivaledGods" PRIMARY KEY ("PlayerId", "ShardId", "ActivityId")
);

CREATE TABLE "PaidOrders" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "PlayerId" bigint NOT NULL,
    "Payload" text NOT NULL,
    "ClaimStatus" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "Awards" text,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_PaidOrders" PRIMARY KEY ("Id")
);

CREATE TABLE "PlatformNotifies" (
    "ShardId" smallint NOT NULL,
    "Id" uuid NOT NULL,
    "PlayerId" bigint NOT NULL,
    "Payload" text NOT NULL,
    "Type" integer NOT NULL,
    "ClaimStatus" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_PlatformNotifies" PRIMARY KEY ("PlayerId", "Id", "ShardId")
);

CREATE TABLE "PromotionStatus" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "LastPromotedPackage" text NOT NULL,
    "PackagePromotionTime" bigint NOT NULL,
    "IceBreakingPayPromotion" integer NOT NULL,
    "DoubleDiamondBonusTriggerRecords" jsonb NOT NULL DEFAULT ('{}'::jsonb),
    CONSTRAINT "PK_PromotionStatus" PRIMARY KEY ("PlayerId", "ShardId")
);

CREATE TABLE "RedisLuaScripts" (
    "Name" text NOT NULL,
    "Sha" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_RedisLuaScripts" PRIMARY KEY ("Name")
);

CREATE TABLE "SeasonRefreshedHistories" (
    "SeasonNumber" integer GENERATED BY DEFAULT AS IDENTITY,
    "RefreshedTime" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_SeasonRefreshedHistories" PRIMARY KEY ("SeasonNumber")
);

CREATE TABLE "ServerDataset" (
    "Id" text NOT NULL,
    "Value" integer NOT NULL,
    CONSTRAINT "PK_ServerDataset" PRIMARY KEY ("Id")
);

CREATE TABLE "SocInfos" (
    "DeviceName" character varying(255) NOT NULL,
    CONSTRAINT "PK_SocInfos" PRIMARY KEY ("DeviceName")
);

CREATE TABLE "UserAchievements" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "ConfigId" integer NOT NULL,
    "Target" text NOT NULL,
    "CurrentIndex" integer NOT NULL,
    "Progress" integer NOT NULL,
    "Received" boolean NOT NULL,
    CONSTRAINT "PK_UserAchievements" PRIMARY KEY ("PlayerId", "ConfigId", "Target", "ShardId")
);

CREATE TABLE "UserAssets" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "CoinCount" integer NOT NULL,
    "DiamondCount" integer NOT NULL,
    "Heroes" integer[] NOT NULL,
    "LevelData_LevelScore" integer NOT NULL,
    "LevelData_Level" integer NOT NULL,
    "LevelData_RewardStatus" bigint NOT NULL,
    "DifficultyData_Levels" integer[] NOT NULL DEFAULT (ARRAY[]::integer[]),
    "DifficultyData_Stars" integer[] NOT NULL DEFAULT (ARRAY[]::integer[]),
    "TimeZoneOffset" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_UserAssets" PRIMARY KEY ("PlayerId", "ShardId")
);

CREATE TABLE "UserAttendances" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "RewardIndex" integer NOT NULL,
    "CreateTime" bigint NOT NULL,
    "TotalLoginDays" integer NOT NULL,
    "LastLoginDate" bigint NOT NULL,
    CONSTRAINT "PK_UserAttendances" PRIMARY KEY ("PlayerId", "ShardId")
);

CREATE TABLE "UserBattlePassInfos" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "PassId" integer NOT NULL,
    "Exp" integer NOT NULL,
    "ClaimStatus" bigint[] NOT NULL,
    "SuperPassLevel" integer NOT NULL,
    CONSTRAINT "PK_UserBattlePassInfos" PRIMARY KEY ("PlayerId", "PassId", "ShardId")
);

CREATE TABLE "UserBeginnerTasks" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "StartTime" bigint NOT NULL,
    "DayIndex" integer NOT NULL,
    "FinishedCount" integer NOT NULL,
    "Received" boolean NOT NULL,
    "TaskList" jsonb NOT NULL DEFAULT ('[]'::jsonb),
    CONSTRAINT "PK_UserBeginnerTasks" PRIMARY KEY ("PlayerId", "ShardId")
);

CREATE TABLE "UserCommodityBoughtRecords" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "CommodityId" integer NOT NULL,
    "Count" integer NOT NULL,
    CONSTRAINT "PK_UserCommodityBoughtRecords" PRIMARY KEY ("PlayerId", "CommodityId", "ShardId")
);

CREATE TABLE "UserCustomCardPools" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "HeroId" integer NOT NULL,
    "CardList" integer[] NOT NULL,
    CONSTRAINT "PK_UserCustomCardPools" PRIMARY KEY ("PlayerId", "ShardId", "HeroId")
);

CREATE TABLE "UserCustomData" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "IntData" character varying(1023) NOT NULL,
    "StrData" character varying(2047) NOT NULL,
    CONSTRAINT "PK_UserCustomData" PRIMARY KEY ("PlayerId", "ShardId")
);

CREATE TABLE "UserDailyStoreIndices" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "Index" integer NOT NULL,
    CONSTRAINT "PK_UserDailyStoreIndices" PRIMARY KEY ("PlayerId", "ShardId")
);

CREATE TABLE "UserDailyStoreItems" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "ItemId" integer NOT NULL,
    "ItemCount" integer NOT NULL,
    "Price" integer NOT NULL,
    "PriceType" integer NOT NULL,
    "TimeStamp" bigint NOT NULL,
    "Bought" boolean NOT NULL,
    CONSTRAINT "PK_UserDailyStoreItems" PRIMARY KEY ("PlayerId", "ItemId", "ShardId")
);

CREATE TABLE "UserDailyTasks" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "TaskRefreshTime" bigint NOT NULL,
    "TaskProgress" integer[] NOT NULL,
    "DailyTaskRewardClaimStatus" integer NOT NULL,
    "ActiveScoreRewardClaimStatus" integer NOT NULL,
    CONSTRAINT "PK_UserDailyTasks" PRIMARY KEY ("PlayerId", "ShardId")
);

CREATE TABLE "UserDailyTreasureBoxProgresses" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "Progress" integer NOT NULL,
    "RewardClaimStatus" integer NOT NULL,
    "Timestamp" bigint NOT NULL,
    CONSTRAINT "PK_UserDailyTreasureBoxProgresses" PRIMARY KEY ("PlayerId", "ShardId")
);

CREATE TABLE "UserDivisions" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "DivisionScore" integer NOT NULL,
    "MaxDivisionScore" integer NOT NULL,
    "LastSeasonNumber" integer NOT NULL,
    "RewardReceived" boolean NOT NULL,
    "LastDivisionScore" integer NOT NULL,
    "LastDivisionRank" integer NOT NULL,
    "LastWorldRank" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_UserDivisions" PRIMARY KEY ("PlayerId", "ShardId")
);

CREATE TABLE "UserEndlessRanks" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "SeasonNumber" integer NOT NULL,
    "SurvivorScore" bigint NOT NULL,
    "SurvivorTimestamp" bigint NOT NULL,
    "TowerDefenceScore" bigint NOT NULL,
    "TowerDefenceTimestamp" bigint NOT NULL,
    "TrueEndlessScore" bigint NOT NULL,
    "TrueEndlessTimestamp" bigint NOT NULL,
    CONSTRAINT "PK_UserEndlessRanks" PRIMARY KEY ("PlayerId", "ShardId", "SeasonNumber")
);

CREATE TABLE "UserFixedLevelMapProgress" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "MapId" integer NOT NULL,
    "StarCount" integer NOT NULL,
    "FinishedTaskList" integer[],
    CONSTRAINT "PK_UserFixedLevelMapProgress" PRIMARY KEY ("PlayerId", "MapId", "ShardId")
);

CREATE TABLE "UserFortuneBagInfos" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "ActivityId" integer NOT NULL,
    "FortuneBags" jsonb NOT NULL DEFAULT ('[]'::jsonb),
    "FortuneLevelRewardClaimStatus" integer NOT NULL,
    CONSTRAINT "PK_UserFortuneBagInfos" PRIMARY KEY ("PlayerId", "ShardId")
);

CREATE TABLE "UserGameInfos" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "LastGameEndTime" bigint NOT NULL,
    "DelayBoxSequence" integer NOT NULL,
    "TicketBoxSequence" integer NOT NULL,
    "DrawNewCardCountList" integer[] NOT NULL DEFAULT (ARRAY[]::integer[]),
    "DrawCardCountList" integer[] NOT NULL DEFAULT (ARRAY[]::integer[]),
    "GeneralCardCountList" integer[] NOT NULL DEFAULT (ARRAY[]::integer[]),
    CONSTRAINT "PK_UserGameInfos" PRIMARY KEY ("PlayerId", "ShardId")
);

CREATE TABLE "UserGlobalInfos" (
    "UserId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "LastLoginPlayerId" bigint NOT NULL,
    CONSTRAINT "PK_UserGlobalInfos" PRIMARY KEY ("UserId")
);

CREATE TABLE "UserIapPurchases" (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "IapItemId" text NOT NULL,
    "WhenPurchased" bigint NOT NULL,
    CONSTRAINT "PK_UserIapPurchases" PRIMARY KEY ("Id", "ShardId")
);

CREATE TABLE "UserIdleRewardInfos" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "StartTime" bigint NOT NULL,
    "StolenRecords" bigint[] NOT NULL,
    "IdleRewardId" integer NOT NULL,
    CONSTRAINT "PK_UserIdleRewardInfos" PRIMARY KEY ("PlayerId", "ShardId")
);

CREATE TABLE "UserInfos" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "UserId" bigint NOT NULL,
    "Signature" character varying(255),
    "HideHistory" boolean NOT NULL,
    "AvatarFrameItemID" integer NOT NULL,
    "NameCardItemID" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_UserInfos" PRIMARY KEY ("PlayerId", "ShardId")
);

CREATE TABLE "UserMallAdvertisements" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "Id" integer NOT NULL,
    "LastTime" bigint NOT NULL DEFAULT 0,
    "Count" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_UserMallAdvertisements" PRIMARY KEY ("PlayerId", "Id", "ShardId")
);

CREATE TABLE "UserMonthPassInfos" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "PassAcquireTime" bigint NOT NULL,
    "PassDayLength" integer NOT NULL,
    "RewardClaimStatus" integer NOT NULL,
    "LastRewardClaimDay" integer NOT NULL,
    CONSTRAINT "PK_UserMonthPassInfos" PRIMARY KEY ("PlayerId", "ShardId")
);

CREATE TABLE "UserRanks" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "SeasonNumber" integer NOT NULL,
    "Division" integer NOT NULL,
    "GroupId" bigint NOT NULL,
    "HighestScore" bigint NOT NULL,
    "Win" boolean NOT NULL,
    "Timestamp" bigint NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_UserRanks" PRIMARY KEY ("PlayerId", "ShardId", "SeasonNumber")
);

CREATE TABLE "UserStarStoreStatus" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "StarRewardClaimStatus" bigint[] NOT NULL,
    CONSTRAINT "PK_UserStarStoreStatus" PRIMARY KEY ("PlayerId", "ShardId")
);

CREATE TABLE "UserCards" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "CardId" integer NOT NULL,
    "CardLevel" integer NOT NULL,
    "CardExp" integer NOT NULL,
    "CardArenaDifficultyReached" integer NOT NULL,
    "CardArenaLevelReached" integer NOT NULL,
    "Timestamp" bigint NOT NULL,
    CONSTRAINT "PK_UserCards" PRIMARY KEY ("PlayerId", "CardId", "ShardId"),
    CONSTRAINT "FK_UserCards_UserAssets_PlayerId_ShardId" FOREIGN KEY ("PlayerId", "ShardId") REFERENCES "UserAssets" ("PlayerId", "ShardId") ON DELETE CASCADE
);

CREATE TABLE "UserItems" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "ItemId" integer NOT NULL,
    "ItemCount" integer NOT NULL,
    CONSTRAINT "PK_UserItems" PRIMARY KEY ("PlayerId", "ItemId", "ShardId"),
    CONSTRAINT "FK_UserItems_UserAssets_PlayerId_ShardId" FOREIGN KEY ("PlayerId", "ShardId") REFERENCES "UserAssets" ("PlayerId", "ShardId") ON DELETE CASCADE
);

CREATE TABLE "UserTreasureBoxes" (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "ItemId" integer NOT NULL,
    "ItemCount" integer NOT NULL,
    "StarCount" integer NOT NULL,
    CONSTRAINT "PK_UserTreasureBoxes" PRIMARY KEY ("Id", "ShardId"),
    CONSTRAINT "FK_UserTreasureBoxes_UserAssets_PlayerId_ShardId" FOREIGN KEY ("PlayerId", "ShardId") REFERENCES "UserAssets" ("PlayerId", "ShardId") ON DELETE CASCADE
);

CREATE TABLE "UserHistories" (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "Timestamp" bigint NOT NULL,
    "GameTime" real NOT NULL,
    "GameStartTime" bigint NOT NULL,
    "MapType" integer NOT NULL,
    "TypedMapId" integer NOT NULL,
    "MapId" integer NOT NULL,
    "Win" boolean NOT NULL,
    "KillCount" integer NOT NULL,
    "MapUnlockRatio" real NOT NULL,
    "Exp" real NOT NULL,
    "Score" integer NOT NULL,
    "Difficulty" integer NOT NULL,
    "ResourceRecords" jsonb NOT NULL DEFAULT ('[]'::jsonb),
    "FightUnitInfos" jsonb NOT NULL DEFAULT ('[]'::jsonb),
    "DynamicInfo" text NOT NULL DEFAULT '{}',
    CONSTRAINT "PK_UserHistories" PRIMARY KEY ("Id", "ShardId"),
    CONSTRAINT "FK_UserHistories_UserInfos_PlayerId_ShardId" FOREIGN KEY ("PlayerId", "ShardId") REFERENCES "UserInfos" ("PlayerId", "ShardId") ON DELETE CASCADE
);

CREATE INDEX "IX_PaidOrders_PlayerId_ClaimStatus" ON "PaidOrders" ("PlayerId", "ClaimStatus");

CREATE INDEX "IX_PlatformNotifies_PlayerId_ClaimStatus_ShardId" ON "PlatformNotifies" ("PlayerId", "ClaimStatus", "ShardId");

CREATE INDEX "IX_UserCards_PlayerId_ShardId" ON "UserCards" ("PlayerId", "ShardId");

CREATE INDEX "IX_UserEndlessRanks_SurvivorScore_SurvivorTimestamp" ON "UserEndlessRanks" ("SurvivorScore" DESC, "SurvivorTimestamp");

CREATE INDEX "IX_UserEndlessRanks_TowerDefenceScore_TowerDefenceTimestamp" ON "UserEndlessRanks" ("TowerDefenceScore" DESC, "TowerDefenceTimestamp");

CREATE INDEX "IX_UserEndlessRanks_TrueEndlessScore_TrueEndlessTimestamp" ON "UserEndlessRanks" ("TrueEndlessScore" DESC, "TrueEndlessTimestamp");

CREATE INDEX "IX_UserHistories_PlayerId" ON "UserHistories" ("PlayerId");

CREATE INDEX "IX_UserHistories_PlayerId_ShardId" ON "UserHistories" ("PlayerId", "ShardId");

CREATE INDEX "IX_UserIapPurchases_PlayerId_ShardId" ON "UserIapPurchases" ("PlayerId", "ShardId");

CREATE INDEX "IX_UserItems_PlayerId_ShardId" ON "UserItems" ("PlayerId", "ShardId");

CREATE INDEX "IX_UserRanks_HighestScore_Timestamp" ON "UserRanks" ("HighestScore" DESC, "Timestamp");

CREATE INDEX "IX_UserRanks_SeasonNumber_Division_GroupId" ON "UserRanks" ("SeasonNumber", "Division", "GroupId");

CREATE INDEX "IX_UserTreasureBoxes_PlayerId_ShardId" ON "UserTreasureBoxes" ("PlayerId", "ShardId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250813094952_InitialCreate', '8.0.21');

COMMIT;

START TRANSACTION;

ALTER TABLE "UserAssets" DROP COLUMN "LevelData_RewardStatus";

ALTER TABLE "UserAssets" ADD "LevelData_RewardStatusList" bigint[] NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250902022935_ChangeUserLevelDataRewardStatusToList', '8.0.21');

COMMIT;

START TRANSACTION;

ALTER TABLE "UserAssets" ALTER COLUMN "LevelData_RewardStatusList" SET DEFAULT (ARRAY[]::bigint[]);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250902024453_UserLevelRewardStatusListBuildDefaultValue', '8.0.21');

COMMIT;

START TRANSACTION;

ALTER TABLE "ActivityPiggyBanks" DROP CONSTRAINT "PK_ActivityPiggyBanks";

ALTER TABLE "ActivityPiggyBanks" ADD CONSTRAINT "PK_ActivityPiggyBanks" PRIMARY KEY ("PlayerId", "ShardId");

CREATE TABLE "UserEncryptionInfos" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "EncryptionKey" text NOT NULL,
    CONSTRAINT "PK_UserEncryptionInfos" PRIMARY KEY ("PlayerId", "ShardId")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250902050313_AddUserEncryptionInfo', '8.0.21');

COMMIT;

START TRANSACTION;

ALTER TABLE "UserGameInfos" ADD "CheatAccumulate" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250903042134_AddCheatAccumulate', '8.0.21');

COMMIT;

START TRANSACTION;

ALTER TABLE "ActivityPiggyBanks" DROP COLUMN "ActivityId";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250904101030_去掉貔貅的activityID', '8.0.21');

COMMIT;

START TRANSACTION;

ALTER TABLE "UserAssets" ADD "LastInDebtTime" bigint NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250905081627_AddLastInDebtTime', '8.0.21');

COMMIT;

START TRANSACTION;

CREATE TABLE "ActivitySlotMachines" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "ActivityId" integer NOT NULL,
    "LastDrawTime" bigint NOT NULL,
    "TodayDrawCount" integer NOT NULL,
    "ActivityPoint" integer NOT NULL,
    "PointRewardClaimStatus" bigint NOT NULL,
    "RewardsInSlot" integer[] NOT NULL,
    "RerollCounts" integer[] NOT NULL,
    "GuaranteeProgressList" integer[] NOT NULL,
    CONSTRAINT "PK_ActivitySlotMachines" PRIMARY KEY ("PlayerId", "ShardId", "ActivityId")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250910100038_activitySlotMachine', '8.0.21');

COMMIT;

START TRANSACTION;

ALTER TABLE "ActivitySlotMachines" ADD "NextDrawRewardDoubledUp" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250915081121_slotMachineDoubleUpRecord', '8.0.21');

COMMIT;

START TRANSACTION;

CREATE TABLE "ActivityTreasureMazeInfos" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "ActivityId" integer NOT NULL,
    "GameKeyCount" integer NOT NULL,
    "LastGameKeyTimestamp" bigint NOT NULL,
    "AwayGameCountToday" integer NOT NULL,
    "LastAwayGameTimestamp" bigint NOT NULL,
    "LevelPassed" integer[] NOT NULL,
    CONSTRAINT "PK_ActivityTreasureMazeInfos" PRIMARY KEY ("PlayerId", "ShardId", "ActivityId")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250926042415_AddActicityTreasureMazeData', '8.0.21');

COMMIT;

START TRANSACTION;

CREATE TABLE "UserH5FriendActivityInfos" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "NextShowingLevel" bigint NOT NULL,
    CONSTRAINT "PK_UserH5FriendActivityInfos" PRIMARY KEY ("PlayerId", "ShardId")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250930102752_AddUserH5FriendActivityInfo', '8.0.21');

COMMIT;

START TRANSACTION;

ALTER TABLE "UserH5FriendActivityInfos" ADD "ClaimedInvitationCode" boolean NOT NULL DEFAULT FALSE;

CREATE TABLE "InvitationCodeClaimRecords" (
    "GiftCode" text NOT NULL,
    CONSTRAINT "PK_InvitationCodeClaimRecords" PRIMARY KEY ("GiftCode")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251012113108_AddInvitationCodeClaimRecords', '8.0.21');

COMMIT;

START TRANSACTION;

CREATE TABLE "InvitationCodeClaimRecords" (
    "GiftCode" text NOT NULL,
    CONSTRAINT "PK_InvitationCodeClaimRecords" PRIMARY KEY ("GiftCode")
);

CREATE TABLE "IosGameCenterRewardInfos" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "RewardClaimed" boolean NOT NULL,
    CONSTRAINT "PK_IosGameCenterRewardInfos" PRIMARY KEY ("PlayerId", "ShardId")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251013063522_AddIosGameCenterRewardInfos', '8.0.21');

COMMIT;

START TRANSACTION;

CREATE TABLE "ActivityOneShotKills" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "ActivityId" integer NOT NULL,
    "MapCompleteRewardClaimStatus" bigint NOT NULL,
    "MapConquerRewardClaimStatus" bigint NOT NULL,
    "OneShotKillUltimateRewardClaimStatus" boolean NOT NULL,
    CONSTRAINT "PK_ActivityOneShotKills" PRIMARY KEY ("PlayerId", "ShardId", "ActivityId")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251014021942_AddOneShotKillActivityData', '8.0.21');

COMMIT;

START TRANSACTION;

ALTER TABLE "UserMonthPassInfos" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now());

ALTER TABLE "UserMonthPassInfos" ADD "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now());

ALTER TABLE "UserH5FriendActivityInfos" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now());

ALTER TABLE "UserH5FriendActivityInfos" ADD "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now());

ALTER TABLE "UserCommodityBoughtRecords" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now());

ALTER TABLE "UserCommodityBoughtRecords" ADD "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now());

ALTER TABLE "UserCards" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now());

ALTER TABLE "UserCards" ADD "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now());

ALTER TABLE "IosGameCenterRewardInfos" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now());

ALTER TABLE "IosGameCenterRewardInfos" ADD "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now());

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251016034848_AddCreatedAtUpdatedAt', '8.0.21');

COMMIT;

START TRANSACTION;

CREATE TABLE "PaidOrderWithShards" (
    "ShardId" smallint NOT NULL,
    "Id" bigint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "Payload" text NOT NULL,
    "ClaimStatus" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "Awards" text,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_PaidOrderWithShards" PRIMARY KEY ("Id", "ShardId")
);

CREATE INDEX "IX_PaidOrderWithShards_PlayerId_ShardId_ClaimStatus" ON "PaidOrderWithShards" ("PlayerId", "ShardId", "ClaimStatus");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251103081215_AddPaidOrderWithShards', '8.0.21');

COMMIT;

START TRANSACTION;

DROP INDEX "IX_UserRanks_SeasonNumber_Division_GroupId";

DROP INDEX "IX_UserEndlessRanks_SurvivorScore_SurvivorTimestamp";

DROP INDEX "IX_UserEndlessRanks_TowerDefenceScore_TowerDefenceTimestamp";

DROP INDEX "IX_UserEndlessRanks_TrueEndlessScore_TrueEndlessTimestamp";

CREATE TABLE "LocalRedisLuaScripts" (
    "ShardId" smallint NOT NULL,
    "Name" text NOT NULL,
    "Sha" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_LocalRedisLuaScripts" PRIMARY KEY ("Name", "ShardId")
);

CREATE INDEX "IX_UserRanks_SeasonNumber_Division_GroupId_ShardId" ON "UserRanks" ("SeasonNumber", "Division", "GroupId", "ShardId");

CREATE INDEX "IX_UserRanks_SeasonNumber_ShardId" ON "UserRanks" ("SeasonNumber", "ShardId");

CREATE INDEX "IX_UserEndlessRanks_SeasonNumber_ShardId" ON "UserEndlessRanks" ("SeasonNumber", "ShardId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251105100524_AddRanksIndex', '8.0.21');

COMMIT;

START TRANSACTION;

ALTER TABLE "ActivityOneShotKills" RENAME COLUMN "MapConquerRewardClaimStatus" TO "TaskCompleteRewardClaimStatus";

ALTER TABLE "ActivityOneShotKills" ADD "AwayGameCountUpdateTimestamp" bigint NOT NULL DEFAULT 0;

ALTER TABLE "ActivityOneShotKills" ADD "GameCountUpdateTimestamp" bigint NOT NULL DEFAULT 0;

ALTER TABLE "ActivityOneShotKills" ADD "MapConquerRewardClaimTimestamp" bigint[] NOT NULL;

ALTER TABLE "ActivityOneShotKills" ADD "TodayAwayGameCount" integer NOT NULL DEFAULT 0;

ALTER TABLE "ActivityOneShotKills" ADD "TodayGameCount" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251107082834_UpdateOneShotKillDataStructure', '8.0.21');

COMMIT;

START TRANSACTION;

ALTER TABLE "ActivitySlotMachines" DROP COLUMN "NextDrawRewardDoubledUp";

ALTER TABLE "ActivitySlotMachines" ALTER COLUMN "RewardsInSlot" SET DEFAULT (ARRAY[]::integer[]);

ALTER TABLE "ActivitySlotMachines" ALTER COLUMN "RerollCounts" SET DEFAULT (ARRAY[]::integer[]);

ALTER TABLE "ActivitySlotMachines" ALTER COLUMN "GuaranteeProgressList" SET DEFAULT (ARRAY[]::integer[]);

ALTER TABLE "ActivitySlotMachines" ADD "RewardDoubledUpItemCount" integer[] NOT NULL DEFAULT (ARRAY[]::integer[]);

ALTER TABLE "ActivityOneShotKills" ALTER COLUMN "MapConquerRewardClaimTimestamp" SET DEFAULT (ARRAY[]::bigint[]);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251112025636_NewSlotMachineDoubleUpData', '8.0.21');

COMMIT;

START TRANSACTION;

ALTER TABLE "UserInfos" ADD "WorldRankHistories" integer[] NOT NULL DEFAULT (ARRAY[]::integer[]);

ALTER TABLE "UserInfos" ADD "WorldRankSeasonHistories" integer[] NOT NULL DEFAULT (ARRAY[]::integer[]);

ALTER TABLE "UserHistories" ALTER COLUMN "Score" TYPE bigint;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251114092000_AddUserInfoWorldRank', '8.0.21');

COMMIT;

START TRANSACTION;

ALTER TABLE "ActivitySlotMachines" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now());

ALTER TABLE "ActivitySlotMachines" ADD "DeletedAt" timestamp with time zone;

ALTER TABLE "ActivitySlotMachines" ADD "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now());

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251120025402_AddSoftDeleteToSlotMachine', '8.0.21');

COMMIT;

START TRANSACTION;

ALTER TABLE "ActivityOneShotKills" ADD "ChallengeVictoryCount" integer NOT NULL DEFAULT 0;

ALTER TABLE "ActivityOneShotKills" ADD "ChallengeVictoryUpdateTimestamp" bigint NOT NULL DEFAULT 0;

ALTER TABLE "ActivityOneShotKills" ADD "NormalVictoryCount" integer NOT NULL DEFAULT 0;

ALTER TABLE "ActivityOneShotKills" ADD "NormalVictoryUpdateTimestamp" bigint NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251126084305_NewRestrictionRuleOnOneShotKill', '8.0.21');

COMMIT;

START TRANSACTION;

ALTER TABLE "UserH5FriendActivityInfos" ADD "NextShowingLevelV1" bigint NOT NULL DEFAULT 0;

CREATE TABLE "PlayerAssistActivityInfos" (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "PlayerId" bigint NOT NULL,
    "ShardId" smallint NOT NULL,
    "DistroId" uuid NOT NULL,
    "ActivityName" text NOT NULL,
    "Payload" jsonb NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_PlayerAssistActivityInfos" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_PlayerAssistActivityInfos_PlayerId_ShardId_DistroId" ON "PlayerAssistActivityInfos" ("PlayerId", "ShardId", "DistroId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251128073906_AddNextShowingLevelV1', '8.0.21');

COMMIT;

START TRANSACTION;

DROP TABLE "PaidOrders";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251201050017_dropPaidOrders', '8.0.21');

COMMIT;

START TRANSACTION;

ALTER TABLE "PlayerAssistActivityInfos" DROP CONSTRAINT "PK_PlayerAssistActivityInfos";

DROP INDEX "IX_PlayerAssistActivityInfos_PlayerId_ShardId_DistroId";

ALTER TABLE "PlayerAssistActivityInfos" DROP COLUMN "Id";

ALTER TABLE "PlayerAssistActivityInfos" ADD CONSTRAINT "PK_PlayerAssistActivityInfos" PRIMARY KEY ("PlayerId", "ShardId", "DistroId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251202023808_modifyAssistActivity', '8.0.21');

COMMIT;

START TRANSACTION;

CREATE TABLE "ActivityTreasureHunts" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "ActivityId" integer NOT NULL,
    "LastRefreshTime" bigint NOT NULL,
    "TodayRefreshCount" integer NOT NULL,
    "ScorePoints" integer NOT NULL,
    "KeyCount" integer NOT NULL,
    "ScoreRewardClaimStatus" bigint NOT NULL,
    "RewardSlots" jsonb NOT NULL DEFAULT ('[]'::jsonb),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_ActivityTreasureHunts" PRIMARY KEY ("PlayerId", "ShardId", "ActivityId")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251219080637_AddTreasureHunt', '8.0.21');

COMMIT;

START TRANSACTION;

ALTER TABLE "ActivityTreasureHunts" ADD "DeletedAt" timestamp with time zone;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251223202013_AddTreasureHuntDeleteAt', '8.0.21');

COMMIT;

START TRANSACTION;

ALTER TABLE "UserGameInfos" ADD "LastArenaBoxRewardTime" bigint NOT NULL DEFAULT 0;

ALTER TABLE "UserGameInfos" ADD "TodayArenaBoxRewardCount" bigint NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251225032925_AddArenaDailyLimit', '8.0.21');

COMMIT;

START TRANSACTION;

CREATE TABLE "ActivityRpgGames" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "ActivityId" integer NOT NULL,
    "LastGameCountRecordTime" bigint NOT NULL,
    "TodayGameCount" integer NOT NULL,
    "LevelPassedStatus" bigint NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_ActivityRpgGames" PRIMARY KEY ("PlayerId", "ShardId", "ActivityId")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251226073114_RpgGameData', '8.0.21');

COMMIT;

START TRANSACTION;

CREATE TABLE "PlayerPunishmentTasks" (
    "TaskId" character varying(128) NOT NULL,
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_PlayerPunishmentTasks" PRIMARY KEY ("PlayerId", "TaskId", "ShardId")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251231064050_AddPlayerPunishmentTasks', '8.0.21');

COMMIT;

START TRANSACTION;

CREATE TABLE "ActivityCsgoStyleLotteryInfos" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "ActivityId" integer NOT NULL,
    "ActivityPoint" integer NOT NULL,
    "PointRewardClaimStatus" bigint NOT NULL,
    "KeyCount" integer NOT NULL,
    "KeyPurchaseCountByDiamond" integer NOT NULL,
    "ActivityPremiumPassStatus" bigint NOT NULL,
    "PremiumPassDailyRewardClaimStatus" bigint[] NOT NULL DEFAULT (ARRAY[]::bigint[]),
    "RewardRecord" integer[] NOT NULL DEFAULT (ARRAY[]::integer[]),
    "TaskRecord" jsonb NOT NULL DEFAULT ('{}'::jsonb),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_ActivityCsgoStyleLotteryInfos" PRIMARY KEY ("PlayerId", "ActivityId", "ShardId")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260112080044_CsgoLottery', '8.0.21');

COMMIT;

START TRANSACTION;

ALTER TABLE "UserCustomCardPools" ADD "ExtraSlotCount" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260113021256_ExtraCardPoolSlot', '8.0.21');

COMMIT;

START TRANSACTION;

CREATE TABLE "ActivityLoogGames" (
    "ShardId" smallint NOT NULL,
    "PlayerId" bigint NOT NULL,
    "ActivityId" integer NOT NULL,
    "LastGameCountRecordTime" bigint NOT NULL,
    "TodayGameCount" integer NOT NULL,
    "LevelPassedStatus" bigint NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_ActivityLoogGames" PRIMARY KEY ("PlayerId", "ShardId", "ActivityId")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260114075847_addActivityLoogGame', '8.0.21');

COMMIT;

START TRANSACTION;

ALTER TABLE "ActivityCsgoStyleLotteryInfos" ADD "DiamondPurchaseCountRefreshTime" bigint NOT NULL DEFAULT 0;

ALTER TABLE "ActivityCsgoStyleLotteryInfos" ADD "RewardRecordTime" bigint[] NOT NULL DEFAULT (ARRAY[]::bigint[]);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260121025402_UpdateCsgoLotteryData', '8.0.21');

COMMIT;

START TRANSACTION;

ALTER TABLE "ActivityCsgoStyleLotteryInfos" RENAME COLUMN "DiamondPurchaseCountRefreshTime" TO "LotteryDrawInfoRefreshTimestamp";

ALTER TABLE "ActivityCsgoStyleLotteryInfos" ADD "TotalLotteryDrawToday" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260123065023_AddDrawLimitForCsgoLottery', '8.0.21');

COMMIT;

