// <auto-generated />
using System;
using System.Collections.Generic;
using GameOutside.DBContext;
using GameOutside.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameOutside.Migrations
{
    [DbContext(typeof(BuildingGameDB))]
    [Migration("20251114092000_AddUserInfoWorldRank")]
    partial class AddUserInfoWorldRank
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChillyRoom.Functions.DBModel.Models.PaidOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Awards")
                        .HasColumnType("text");

                    b.Property<int>("ClaimStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "ClaimStatus");

                    b.ToTable("PaidOrders");
                });

            modelBuilder.Entity("ChillyRoom.Functions.DBModel.Models.PaidOrderWithShard", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<string>("Awards")
                        .HasColumnType("text");

                    b.Property<int>("ClaimStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id", "ShardId");

                    b.HasIndex("PlayerId", "ShardId", "ClaimStatus");

                    b.ToTable("PaidOrderWithShards");
                });

            modelBuilder.Entity("ChillyRoom.Functions.DBModel.Models.PlatformNotify", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<int>("ClaimStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("PlayerId", "Id", "ShardId");

                    b.HasIndex("PlayerId", "ClaimStatus", "ShardId");

                    b.ToTable("PlatformNotifies");
                });

            modelBuilder.Entity("GameOutside.Models.ActivityCoopBossInfo", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<int>("ActivityId")
                        .HasColumnType("integer");

                    b.Property<int>("DrewCount")
                        .HasColumnType("integer");

                    b.Property<int>("GameEndCountToday")
                        .HasColumnType("integer");

                    b.Property<int>("LastLevel")
                        .HasColumnType("integer");

                    b.Property<long>("LastLevelActivateTime")
                        .HasColumnType("bigint");

                    b.Property<long>("LastRefreshEndCountTime")
                        .HasColumnType("bigint");

                    b.Property<long>("LastRefreshTime")
                        .HasColumnType("bigint");

                    b.Property<int>("RefreshCountToday")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "ShardId", "ActivityId");

                    b.ToTable("ActivityCoopBossInfoSet");
                });

            modelBuilder.Entity("GameOutside.Models.ActivityEndlessChallenge", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<int>("ActivityId")
                        .HasColumnType("integer");

                    b.Property<long>("LastGameTime")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxUnlockDifficulty")
                        .HasColumnType("integer");

                    b.Property<int>("TodayGameCount")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "ShardId", "ActivityId");

                    b.ToTable("ActivityEndlessChallenges");
                });

            modelBuilder.Entity("GameOutside.Models.ActivityLuckyStar", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<int>("ActivityId")
                        .HasColumnType("integer");

                    b.Property<int>("Cycle")
                        .HasColumnType("integer");

                    b.Property<bool>("Free")
                        .HasColumnType("boolean");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "ShardId");

                    b.ToTable("ActivityLuckyStars");
                });

            modelBuilder.Entity("GameOutside.Models.ActivityOneShotKill", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<int>("ActivityId")
                        .HasColumnType("integer");

                    b.Property<long>("AwayGameCountUpdateTimestamp")
                        .HasColumnType("bigint");

                    b.Property<long>("GameCountUpdateTimestamp")
                        .HasColumnType("bigint");

                    b.Property<long>("MapCompleteRewardClaimStatus")
                        .HasColumnType("bigint");

                    b.Property<List<long>>("MapConquerRewardClaimTimestamp")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint[]")
                        .HasDefaultValueSql("ARRAY[]::bigint[]");

                    b.Property<bool>("OneShotKillUltimateRewardClaimStatus")
                        .HasColumnType("boolean");

                    b.Property<long>("TaskCompleteRewardClaimStatus")
                        .HasColumnType("bigint");

                    b.Property<int>("TodayAwayGameCount")
                        .HasColumnType("integer");

                    b.Property<int>("TodayGameCount")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "ShardId", "ActivityId");

                    b.ToTable("ActivityOneShotKills");
                });

            modelBuilder.Entity("GameOutside.Models.ActivityPiggyBank", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<List<long>>("ClaimStatus")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.Property<int>("Exp")
                        .HasColumnType("integer");

                    b.Property<int>("PaidLevel")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "ShardId");

                    b.ToTable("ActivityPiggyBanks");
                });

            modelBuilder.Entity("GameOutside.Models.ActivitySlotMachine", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<int>("ActivityId")
                        .HasColumnType("integer");

                    b.Property<int>("ActivityPoint")
                        .HasColumnType("integer");

                    b.Property<List<int>>("GuaranteeProgressList")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer[]")
                        .HasDefaultValueSql("ARRAY[]::integer[]");

                    b.Property<long>("LastDrawTime")
                        .HasColumnType("bigint");

                    b.Property<long>("PointRewardClaimStatus")
                        .HasColumnType("bigint");

                    b.Property<List<int>>("RerollCounts")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer[]")
                        .HasDefaultValueSql("ARRAY[]::integer[]");

                    b.Property<List<int>>("RewardDoubledUpItemCount")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer[]")
                        .HasDefaultValueSql("ARRAY[]::integer[]");

                    b.Property<List<int>>("RewardsInSlot")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer[]")
                        .HasDefaultValueSql("ARRAY[]::integer[]");

                    b.Property<int>("TodayDrawCount")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "ShardId", "ActivityId");

                    b.ToTable("ActivitySlotMachines");
                });

            modelBuilder.Entity("GameOutside.Models.ActivityTreasureMaze", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<int>("ActivityId")
                        .HasColumnType("integer");

                    b.Property<int>("AwayGameCountToday")
                        .HasColumnType("integer");

                    b.Property<int>("GameKeyCount")
                        .HasColumnType("integer");

                    b.Property<long>("LastAwayGameTimestamp")
                        .HasColumnType("bigint");

                    b.Property<long>("LastGameKeyTimestamp")
                        .HasColumnType("bigint");

                    b.Property<List<int>>("LevelPassed")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("PlayerId", "ShardId", "ActivityId");

                    b.ToTable("ActivityTreasureMazeInfos");
                });

            modelBuilder.Entity("GameOutside.Models.ActivityUnrivaledGod", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<int>("ActivityId")
                        .HasColumnType("integer");

                    b.Property<Dictionary<int, int>>("ExchangeRecord")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<int>("GuaranteeProgress")
                        .HasColumnType("integer");

                    b.Property<int>("KeyCount")
                        .HasColumnType("integer");

                    b.Property<int>("ScorePoint")
                        .HasColumnType("integer");

                    b.Property<Dictionary<string, UnrivaledGodTask>>("TaskRecord")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.HasKey("PlayerId", "ShardId", "ActivityId");

                    b.ToTable("ActivityUnrivaledGods");
                });

            modelBuilder.Entity("GameOutside.Models.InvitationCodeClaimRecord", b =>
                {
                    b.Property<string>("GiftCode")
                        .HasColumnType("text");

                    b.HasKey("GiftCode");

                    b.ToTable("InvitationCodeClaimRecords");
                });

            modelBuilder.Entity("GameOutside.Models.IosGameCenterRewardInfo", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("RewardClaimed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("PlayerId", "ShardId");

                    b.ToTable("IosGameCenterRewardInfos");
                });

            modelBuilder.Entity("GameOutside.Models.LocalRedisLuaScript", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Name", "ShardId");

                    b.ToTable("LocalRedisLuaScripts");
                });

            modelBuilder.Entity("GameOutside.Models.MonthPassInfo", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("LastRewardClaimDay")
                        .HasColumnType("integer");

                    b.Property<long>("PassAcquireTime")
                        .HasColumnType("bigint");

                    b.Property<int>("PassDayLength")
                        .HasColumnType("integer");

                    b.Property<int>("RewardClaimStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("PlayerId", "ShardId");

                    b.ToTable("UserMonthPassInfos");
                });

            modelBuilder.Entity("GameOutside.Models.RedisLuaScript", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Name");

                    b.ToTable("RedisLuaScripts");
                });

            modelBuilder.Entity("GameOutside.Models.SeasonRefreshedHistory", b =>
                {
                    b.Property<int>("SeasonNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SeasonNumber"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RefreshedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("SeasonNumber");

                    b.ToTable("SeasonRefreshedHistories");
                });

            modelBuilder.Entity("GameOutside.Models.ServerData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ServerDataset");
                });

            modelBuilder.Entity("GameOutside.Models.SocInfo", b =>
                {
                    b.Property<string>("DeviceName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("DeviceName");

                    b.ToTable("SocInfos");
                });

            modelBuilder.Entity("GameOutside.Models.UserAchievement", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("ConfigId")
                        .HasColumnType("integer");

                    b.Property<string>("Target")
                        .HasColumnType("text");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<int>("CurrentIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.Property<bool>("Received")
                        .HasColumnType("boolean");

                    b.HasKey("PlayerId", "ConfigId", "Target", "ShardId");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("GameOutside.Models.UserAssets", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<int>("CoinCount")
                        .HasColumnType("integer");

                    b.Property<int>("DiamondCount")
                        .HasColumnType("integer");

                    b.Property<List<int>>("Heroes")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<long>("LastInDebtTime")
                        .HasColumnType("bigint");

                    b.Property<int>("TimeZoneOffset")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("PlayerId", "ShardId");

                    b.ToTable("UserAssets");
                });

            modelBuilder.Entity("GameOutside.Models.UserAttendance", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<long>("CreateTime")
                        .HasColumnType("bigint");

                    b.Property<long>("LastLoginDate")
                        .HasColumnType("bigint");

                    b.Property<int>("RewardIndex")
                        .HasColumnType("integer");

                    b.Property<int>("TotalLoginDays")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "ShardId");

                    b.ToTable("UserAttendances");
                });

            modelBuilder.Entity("GameOutside.Models.UserBattlePassInfo", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("PassId")
                        .HasColumnType("integer");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<List<long>>("ClaimStatus")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.Property<int>("Exp")
                        .HasColumnType("integer");

                    b.Property<int>("SuperPassLevel")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "PassId", "ShardId");

                    b.ToTable("UserBattlePassInfos");
                });

            modelBuilder.Entity("GameOutside.Models.UserBeginnerTask", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<int>("DayIndex")
                        .HasColumnType("integer");

                    b.Property<int>("FinishedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Received")
                        .HasColumnType("boolean");

                    b.Property<long>("StartTime")
                        .HasColumnType("bigint");

                    b.Property<List<BeginnerTaskData>>("TaskList")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.HasKey("PlayerId", "ShardId");

                    b.ToTable("UserBeginnerTasks");
                });

            modelBuilder.Entity("GameOutside.Models.UserCard", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("CardId")
                        .HasColumnType("integer");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<int>("CardArenaDifficultyReached")
                        .HasColumnType("integer");

                    b.Property<int>("CardArenaLevelReached")
                        .HasColumnType("integer");

                    b.Property<int>("CardExp")
                        .HasColumnType("integer");

                    b.Property<int>("CardLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("PlayerId", "CardId", "ShardId");

                    b.HasIndex("PlayerId", "ShardId");

                    b.ToTable("UserCards");
                });

            modelBuilder.Entity("GameOutside.Models.UserCommodityBoughtRecord", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("CommodityId")
                        .HasColumnType("integer");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("PlayerId", "CommodityId", "ShardId");

                    b.ToTable("UserCommodityBoughtRecords");
                });

            modelBuilder.Entity("GameOutside.Models.UserCustomCardPool", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<int>("HeroId")
                        .HasColumnType("integer");

                    b.Property<List<int>>("CardList")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("PlayerId", "ShardId", "HeroId");

                    b.ToTable("UserCustomCardPools");
                });

            modelBuilder.Entity("GameOutside.Models.UserCustomData", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<string>("IntData")
                        .IsRequired()
                        .HasMaxLength(1023)
                        .HasColumnType("character varying(1023)");

                    b.Property<string>("StrData")
                        .IsRequired()
                        .HasMaxLength(2047)
                        .HasColumnType("character varying(2047)");

                    b.HasKey("PlayerId", "ShardId");

                    b.ToTable("UserCustomData");
                });

            modelBuilder.Entity("GameOutside.Models.UserDailyStoreIndex", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "ShardId");

                    b.ToTable("UserDailyStoreIndices");
                });

            modelBuilder.Entity("GameOutside.Models.UserDailyStoreItem", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<bool>("Bought")
                        .HasColumnType("boolean");

                    b.Property<int>("ItemCount")
                        .HasColumnType("integer");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("PriceType")
                        .HasColumnType("integer");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("bigint");

                    b.HasKey("PlayerId", "ItemId", "ShardId");

                    b.ToTable("UserDailyStoreItems");
                });

            modelBuilder.Entity("GameOutside.Models.UserDailyTask", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<int>("ActiveScoreRewardClaimStatus")
                        .HasColumnType("integer");

                    b.Property<int>("DailyTaskRewardClaimStatus")
                        .HasColumnType("integer");

                    b.Property<List<int>>("TaskProgress")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<long>("TaskRefreshTime")
                        .HasColumnType("bigint");

                    b.HasKey("PlayerId", "ShardId");

                    b.ToTable("UserDailyTasks");
                });

            modelBuilder.Entity("GameOutside.Models.UserDailyTreasureBoxProgress", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.Property<int>("RewardClaimStatus")
                        .HasColumnType("integer");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.HasKey("PlayerId", "ShardId");

                    b.ToTable("UserDailyTreasureBoxProgresses");
                });

            modelBuilder.Entity("GameOutside.Models.UserDivision", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DivisionScore")
                        .HasColumnType("integer");

                    b.Property<int>("LastDivisionRank")
                        .HasColumnType("integer");

                    b.Property<int>("LastDivisionScore")
                        .HasColumnType("integer");

                    b.Property<int>("LastSeasonNumber")
                        .HasColumnType("integer");

                    b.Property<int>("LastWorldRank")
                        .HasColumnType("integer");

                    b.Property<int>("MaxDivisionScore")
                        .HasColumnType("integer");

                    b.Property<bool>("RewardReceived")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("PlayerId", "ShardId");

                    b.ToTable("UserDivisions");
                });

            modelBuilder.Entity("GameOutside.Models.UserEncryptionInfo", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<string>("EncryptionKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PlayerId", "ShardId");

                    b.ToTable("UserEncryptionInfos");
                });

            modelBuilder.Entity("GameOutside.Models.UserEndlessRank", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<long>("SurvivorScore")
                        .HasColumnType("bigint");

                    b.Property<long>("SurvivorTimestamp")
                        .HasColumnType("bigint");

                    b.Property<long>("TowerDefenceScore")
                        .HasColumnType("bigint");

                    b.Property<long>("TowerDefenceTimestamp")
                        .HasColumnType("bigint");

                    b.Property<long>("TrueEndlessScore")
                        .HasColumnType("bigint");

                    b.Property<long>("TrueEndlessTimestamp")
                        .HasColumnType("bigint");

                    b.HasKey("PlayerId", "ShardId", "SeasonNumber");

                    b.HasIndex("SeasonNumber", "ShardId");

                    b.ToTable("UserEndlessRanks");
                });

            modelBuilder.Entity("GameOutside.Models.UserFixedLevelMapProgress", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("MapId")
                        .HasColumnType("integer");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<List<int>>("FinishedTaskList")
                        .HasColumnType("integer[]");

                    b.Property<int>("StarCount")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "MapId", "ShardId");

                    b.ToTable("UserFixedLevelMapProgress");
                });

            modelBuilder.Entity("GameOutside.Models.UserFortuneBagInfo", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<int>("ActivityId")
                        .HasColumnType("integer");

                    b.Property<List<FortuneBagAcquireInfo>>("FortuneBags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<int>("FortuneLevelRewardClaimStatus")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "ShardId");

                    b.ToTable("UserFortuneBagInfos");
                });

            modelBuilder.Entity("GameOutside.Models.UserGameInfo", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<int>("CheatAccumulate")
                        .HasColumnType("integer");

                    b.Property<int>("DelayBoxSequence")
                        .HasColumnType("integer");

                    b.Property<List<int>>("DrawCardCountList")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer[]")
                        .HasDefaultValueSql("ARRAY[]::integer[]");

                    b.Property<List<int>>("DrawNewCardCountList")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer[]")
                        .HasDefaultValueSql("ARRAY[]::integer[]");

                    b.Property<List<int>>("GeneralCardCountList")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer[]")
                        .HasDefaultValueSql("ARRAY[]::integer[]");

                    b.Property<long>("LastGameEndTime")
                        .HasColumnType("bigint");

                    b.Property<int>("TicketBoxSequence")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "ShardId");

                    b.ToTable("UserGameInfos");
                });

            modelBuilder.Entity("GameOutside.Models.UserGlobalInfo", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<long>("LastLoginPlayerId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId");

                    b.ToTable("UserGlobalInfos");
                });

            modelBuilder.Entity("GameOutside.Models.UserH5FriendActivityInfo", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<bool>("ClaimedInvitationCode")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("NextShowingLevel")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("PlayerId", "ShardId");

                    b.ToTable("UserH5FriendActivityInfos");
                });

            modelBuilder.Entity("GameOutside.Models.UserHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("DynamicInfo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{}");

                    b.Property<float>("Exp")
                        .HasColumnType("real");

                    b.Property<List<HistoryFightUnitInfo>>("FightUnitInfos")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<long>("GameStartTime")
                        .HasColumnType("bigint");

                    b.Property<float>("GameTime")
                        .HasColumnType("real");

                    b.Property<int>("KillCount")
                        .HasColumnType("integer");

                    b.Property<int>("MapId")
                        .HasColumnType("integer");

                    b.Property<int>("MapType")
                        .HasColumnType("integer");

                    b.Property<float>("MapUnlockRatio")
                        .HasColumnType("real");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<List<HistoryResourceRecord>>("ResourceRecords")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<long>("Score")
                        .HasColumnType("bigint");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<int>("TypedMapId")
                        .HasColumnType("integer");

                    b.Property<bool>("Win")
                        .HasColumnType("boolean");

                    b.HasKey("Id", "ShardId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PlayerId", "ShardId");

                    b.ToTable("UserHistories");
                });

            modelBuilder.Entity("GameOutside.Models.UserIapPurchaseRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<string>("IapItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<long>("WhenPurchased")
                        .HasColumnType("bigint");

                    b.HasKey("Id", "ShardId");

                    b.HasIndex("PlayerId", "ShardId");

                    b.ToTable("UserIapPurchases");
                });

            modelBuilder.Entity("GameOutside.Models.UserIdleRewardInfo", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<int>("IdleRewardId")
                        .HasColumnType("integer");

                    b.Property<long>("StartTime")
                        .HasColumnType("bigint");

                    b.Property<List<long>>("StolenRecords")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.HasKey("PlayerId", "ShardId");

                    b.ToTable("UserIdleRewardInfos");
                });

            modelBuilder.Entity("GameOutside.Models.UserInfo", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<int>("AvatarFrameItemID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HideHistory")
                        .HasColumnType("boolean");

                    b.Property<int>("NameCardItemID")
                        .HasColumnType("integer");

                    b.Property<string>("Signature")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<List<int>>("WorldRankHistories")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer[]")
                        .HasDefaultValueSql("ARRAY[]::integer[]");

                    b.Property<List<int>>("WorldRankSeasonHistories")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer[]")
                        .HasDefaultValueSql("ARRAY[]::integer[]");

                    b.HasKey("PlayerId", "ShardId");

                    b.ToTable("UserInfos");
                });

            modelBuilder.Entity("GameOutside.Models.UserItem", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<int>("ItemCount")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "ItemId", "ShardId");

                    b.HasIndex("PlayerId", "ShardId");

                    b.ToTable("UserItems");
                });

            modelBuilder.Entity("GameOutside.Models.UserMallAdvertisement", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<int>("Count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<long>("LastTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("PlayerId", "Id", "ShardId");

                    b.ToTable("UserMallAdvertisements");
                });

            modelBuilder.Entity("GameOutside.Models.UserPaymentAndPromotionStatus", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<Dictionary<string, long>>("DoubleDiamondBonusTriggerRecords")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<int>("IceBreakingPayPromotion")
                        .HasColumnType("integer");

                    b.Property<string>("LastPromotedPackage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("PackagePromotionTime")
                        .HasColumnType("bigint");

                    b.HasKey("PlayerId", "ShardId");

                    b.ToTable("PromotionStatus");
                });

            modelBuilder.Entity("GameOutside.Models.UserRank", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Division")
                        .HasColumnType("integer");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<long>("HighestScore")
                        .HasColumnType("bigint");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Win")
                        .HasColumnType("boolean");

                    b.HasKey("PlayerId", "ShardId", "SeasonNumber");

                    b.HasIndex("HighestScore", "Timestamp")
                        .IsDescending(true, false);

                    b.HasIndex("SeasonNumber", "ShardId");

                    b.HasIndex("SeasonNumber", "Division", "GroupId", "ShardId");

                    b.ToTable("UserRanks");
                });

            modelBuilder.Entity("GameOutside.Models.UserStarStoreInfo", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<List<long>>("StarRewardClaimStatus")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.HasKey("PlayerId", "ShardId");

                    b.ToTable("UserStarStoreStatus");
                });

            modelBuilder.Entity("GameOutside.Models.UserTreasureBox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<short>("ShardId")
                        .HasColumnType("smallint");

                    b.Property<int>("ItemCount")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("StarCount")
                        .HasColumnType("integer");

                    b.HasKey("Id", "ShardId");

                    b.HasIndex("PlayerId", "ShardId");

                    b.ToTable("UserTreasureBoxes");
                });

            modelBuilder.Entity("GameOutside.Models.UserAssets", b =>
                {
                    b.OwnsOne("GameOutside.Models.UserDifficultyData", "DifficultyData", b1 =>
                        {
                            b1.Property<long>("UserAssetsPlayerId")
                                .HasColumnType("bigint");

                            b1.Property<short>("UserAssetsShardId")
                                .HasColumnType("smallint");

                            b1.Property<List<int>>("Levels")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer[]")
                                .HasDefaultValueSql("ARRAY[]::integer[]");

                            b1.Property<List<int>>("Stars")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer[]")
                                .HasDefaultValueSql("ARRAY[]::integer[]");

                            b1.HasKey("UserAssetsPlayerId", "UserAssetsShardId");

                            b1.ToTable("UserAssets");

                            b1.WithOwner()
                                .HasForeignKey("UserAssetsPlayerId", "UserAssetsShardId");
                        });

                    b.OwnsOne("GameOutside.Models.UserLevelData", "LevelData", b1 =>
                        {
                            b1.Property<long>("UserAssetsPlayerId")
                                .HasColumnType("bigint");

                            b1.Property<short>("UserAssetsShardId")
                                .HasColumnType("smallint");

                            b1.Property<int>("Level")
                                .HasColumnType("integer");

                            b1.Property<int>("LevelScore")
                                .HasColumnType("integer");

                            b1.Property<List<long>>("RewardStatusList")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint[]")
                                .HasDefaultValueSql("ARRAY[]::bigint[]");

                            b1.HasKey("UserAssetsPlayerId", "UserAssetsShardId");

                            b1.ToTable("UserAssets");

                            b1.WithOwner()
                                .HasForeignKey("UserAssetsPlayerId", "UserAssetsShardId");
                        });

                    b.Navigation("DifficultyData")
                        .IsRequired();

                    b.Navigation("LevelData")
                        .IsRequired();
                });

            modelBuilder.Entity("GameOutside.Models.UserCard", b =>
                {
                    b.HasOne("GameOutside.Models.UserAssets", null)
                        .WithMany("UserCards")
                        .HasForeignKey("PlayerId", "ShardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameOutside.Models.UserHistory", b =>
                {
                    b.HasOne("GameOutside.Models.UserInfo", null)
                        .WithMany("Histories")
                        .HasForeignKey("PlayerId", "ShardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameOutside.Models.UserItem", b =>
                {
                    b.HasOne("GameOutside.Models.UserAssets", null)
                        .WithMany("UserItems")
                        .HasForeignKey("PlayerId", "ShardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameOutside.Models.UserTreasureBox", b =>
                {
                    b.HasOne("GameOutside.Models.UserAssets", null)
                        .WithMany("UserTreasureBoxes")
                        .HasForeignKey("PlayerId", "ShardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameOutside.Models.UserAssets", b =>
                {
                    b.Navigation("UserCards");

                    b.Navigation("UserItems");

                    b.Navigation("UserTreasureBoxes");
                });

            modelBuilder.Entity("GameOutside.Models.UserInfo", b =>
                {
                    b.Navigation("Histories");
                });
#pragma warning restore 612, 618
        }
    }
}
